"""Generate databricks.local.yml from the Databricks CLI profile's host.

The workspace host is intentionally kept out of the committed databricks.yml
(it is supplied via a git-ignored ``*.local.yml`` include). This task resolves
the host for the configured profile via ``databricks auth env`` and writes it
to ``databricks.local.yml`` so the Databricks VS Code extension has what it
needs without anyone hardcoding a URL in version control.

Profile resolution order:
  1. ``DATABRICKS_CONFIG_PROFILE`` environment variable
  2. the ``dev`` profile (repo default)

The generated file is not overwritten if it already exists unless ``--force``
is passed.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

from _tools import find_executable

TARGET = "dev"


def resolve_host(databricks: str, profile: str) -> str | None:
    """Return the workspace host for a profile, or None if unavailable."""
    result = subprocess.run(  # noqa: S603
        [databricks, "auth", "describe", "--profile", profile, "-o", "json"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        return None
    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError:
        return None
    host = (data.get("details") or {}).get("host")
    return host or None


def main() -> None:
    force = "--force" in sys.argv[1:]
    root = Path(__file__).resolve().parent.parent
    out = root / "databricks.local.yml"

    if out.exists() and not force:
        print(f"==> {out.name} already exists; pass --force to overwrite. Skipping.")
        return

    profile = os.environ.get("DATABRICKS_CONFIG_PROFILE", TARGET)
    databricks = find_executable("databricks")

    print(f"==> Resolving host for profile '{profile}'")
    host = resolve_host(databricks, profile)
    if not host:
        raise SystemExit(
            f"ERROR: could not resolve DATABRICKS_HOST for profile '{profile}'. "
            "Check ~/.databrickscfg and that 'az login' / profile auth is valid."
        )

    content = (
        "# Machine-specific overrides — NOT committed (see .gitignore: *.local.yml).\n"
        f"# Generated by 'mise run gen-local-config' from the '{profile}' profile.\n"
        "targets:\n"
        f"  {TARGET}:\n"
        "    workspace:\n"
        f"      host: {host}\n"
    )
    out.write_text(content)
    print(f"==> Wrote {out.name} (host: {host})")


if __name__ == "__main__":
    main()
